name: admin_ib
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_sign_in:
  firebase_auth:
  # fluttertoast:
  # line_icons:
  font_awesome_flutter: any
  # firebase_messaging:
  google_mobile_ads: ^3.1.0
  google_fonts: ^4.0.4
  # url_launcher:
  # share:
  http: ^0.13.3
  file_picker: any
  # shared_preferences: ^2.0.8
dev_dependencies:
  build_web_compilers: ">=2.0.0 <3.0.0"
  pedantic: ^1.11.0

  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    # - lib/assets/animations/splashscreen.json
  
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
  android: true
  ios: true
